import 'package:totalUnit/feature/domain/enums/currency_unit.dart';

extension CurrencyUnitExtension on CurrencyUnit {
  String get code => name.toUpperCase().replaceAll('_', '');
  String get label {
    switch (this) {
      case CurrencyUnit.usd: return "US Dollar";
      case CurrencyUnit.aed: return "UAE Dirham";
      case CurrencyUnit.afn: return "Afghan Afghani";
      case CurrencyUnit.all: return "Albanian Lek";
      case CurrencyUnit.amd: return "Armenian Dram";
      case CurrencyUnit.ang: return "Netherlands Antillean Guilder";
      case CurrencyUnit.aoa: return "Angolan Kwanza";
      case CurrencyUnit.ars: return "Argentine Peso";
      case CurrencyUnit.aud: return "Australian Dollar";
      case CurrencyUnit.awg: return "Aruban Florin";
      case CurrencyUnit.azn: return "Azerbaijani Manat";
      case CurrencyUnit.bam: return "Bosnia-Herzegovina Mark";
      case CurrencyUnit.bbd: return "Barbadian Dollar";
      case CurrencyUnit.bdt: return "Bangladeshi Taka";
      case CurrencyUnit.bgn: return "Bulgarian Lev";
      case CurrencyUnit.bhd: return "Bahraini Dinar";
      case CurrencyUnit.bif: return "Burundian Franc";
      case CurrencyUnit.bmd: return "Bermudan Dollar";
      case CurrencyUnit.bnd: return "Brunei Dollar";
      case CurrencyUnit.bob: return "Bolivian Boliviano";
      case CurrencyUnit.brl: return "Brazilian Real";
      case CurrencyUnit.bsd: return "Bahamian Dollar";
      case CurrencyUnit.btn: return "Bhutanese Ngultrum";
      case CurrencyUnit.bwp: return "Botswanan Pula";
      case CurrencyUnit.byn: return "Belarusian Ruble";
      case CurrencyUnit.bzd: return "Belize Dollar";
      case CurrencyUnit.cad: return "Canadian Dollar";
      case CurrencyUnit.cdf: return "Congolese Franc";
      case CurrencyUnit.chf: return "Swiss Franc";
      case CurrencyUnit.clf: return "Chilean Unit of Account";
      case CurrencyUnit.clp: return "Chilean Peso";
      case CurrencyUnit.cnh: return "Chinese Yuan (Offshore)";
      case CurrencyUnit.cny: return "Chinese Yuan";
      case CurrencyUnit.cop: return "Colombian Peso";
      case CurrencyUnit.crc: return "Costa Rican Colón";
      case CurrencyUnit.cup: return "Cuban Peso";
      case CurrencyUnit.cve: return "Cape Verdean Escudo";
      case CurrencyUnit.czk: return "Czech Koruna";
      case CurrencyUnit.djf: return "Djiboutian Franc";
      case CurrencyUnit.dkk: return "Danish Krone";
      case CurrencyUnit.dop: return "Dominican Peso";
      case CurrencyUnit.dzd: return "Algerian Dinar";
      case CurrencyUnit.egp: return "Egyptian Pound";
      case CurrencyUnit.ern: return "Eritrean Nakfa";
      case CurrencyUnit.etb: return "Ethiopian Birr";
      case CurrencyUnit.eur: return "Euro";
      case CurrencyUnit.fjd: return "Fijian Dollar";
      case CurrencyUnit.fkp: return "Falkland Islands Pound";
      case CurrencyUnit.fok: return "Faroese Króna";
      case CurrencyUnit.gbp: return "British Pound";
      case CurrencyUnit.gel: return "Georgian Lari";
      case CurrencyUnit.ggp: return "Guernsey Pound";
      case CurrencyUnit.ghs: return "Ghanaian Cedi";
      case CurrencyUnit.gip: return "Gibraltar Pound";
      case CurrencyUnit.gmd: return "Gambian Dalasi";
      case CurrencyUnit.gnf: return "Guinean Franc";
      case CurrencyUnit.gtq: return "Guatemalan Quetzal";
      case CurrencyUnit.gyd: return "Guyanese Dollar";
      case CurrencyUnit.hkd: return "Hong Kong Dollar";
      case CurrencyUnit.hnl: return "Honduran Lempira";
      case CurrencyUnit.hrk: return "Croatian Kuna";
      case CurrencyUnit.htg: return "Haitian Gourde";
      case CurrencyUnit.huf: return "Hungarian Forint";
      case CurrencyUnit.idr: return "Indonesian Rupiah";
      case CurrencyUnit.ils: return "Israeli New Shekel";
      case CurrencyUnit.imp: return "Isle of Man Pound";
      case CurrencyUnit.inr: return "Indian Rupee";
      case CurrencyUnit.iqd: return "Iraqi Dinar";
      case CurrencyUnit.irr: return "Iranian Rial";
      case CurrencyUnit.isk: return "Icelandic Krónα";
      case CurrencyUnit.jep: return "Jersey Pound";
      case CurrencyUnit.jmd: return "Jamaican Dollar";
      case CurrencyUnit.jod: return "Jordanian Dinar";
      case CurrencyUnit.jpy: return "Japanese Yen";
      case CurrencyUnit.kes: return "Kenyan Shilling";
      case CurrencyUnit.kgs: return "Kyrgyzstani Som";
      case CurrencyUnit.khr: return "Cambodian Riel";
      case CurrencyUnit.kid: return "Kiribati Dollar";
      case CurrencyUnit.kmf: return "Comorian Franc";
      case CurrencyUnit.krw: return "South Korean Won";
      case CurrencyUnit.kwd: return "Kuwaiti Dinar";
      case CurrencyUnit.kyd: return "Cayman Islands Dollar";
      case CurrencyUnit.kzt: return "Kazakhstani Tenge";
      case CurrencyUnit.lak: return "Lao Kip";
      case CurrencyUnit.lbp: return "Lebanese Pound";
      case CurrencyUnit.lkr: return "Sri Lankan Rupee";
      case CurrencyUnit.lrd: return "Liberian Dollar";
      case CurrencyUnit.lsl: return "Lesotho Loti";
      case CurrencyUnit.lyd: return "Libyan Dinar";
      case CurrencyUnit.mad: return "Moroccan Dirham";
      case CurrencyUnit.mdl: return "Moldovan Leu";
      case CurrencyUnit.mga: return "Malagasy Ariary";
      case CurrencyUnit.mkd: return "Macedonian Denar";
      case CurrencyUnit.mmk: return "Myanmar Kyat";
      case CurrencyUnit.mnt: return "Mongolian Tughrik";
      case CurrencyUnit.mop: return "Macanese Pataca";
      case CurrencyUnit.mru: return "Mauritanian Ouguiya";
      case CurrencyUnit.mur: return "Mauritian Rupee";
      case CurrencyUnit.mvr: return "Maldivian Rufiyaa";
      case CurrencyUnit.mwk: return "Malawian Kwacha";
      case CurrencyUnit.mxn: return "Mexican Peso";
      case CurrencyUnit.myr: return "Malaysian Ringgit";
      case CurrencyUnit.mzn: return "Mozambican Metical";
      case CurrencyUnit.nad: return "Namibian Dollar";
      case CurrencyUnit.ngn: return "Nigerian Naira";
      case CurrencyUnit.nio: return "Nicaraguan Córdoba";
      case CurrencyUnit.nok: return "Norwegian Krone";
      case CurrencyUnit.npr: return "Nepalese Rupee";
      case CurrencyUnit.nzd: return "New Zealand Dollar";
      case CurrencyUnit.omr: return "Omani Rial";
      case CurrencyUnit.pab: return "Panamanian Balboa";
      case CurrencyUnit.pen: return "Peruvian Sol";
      case CurrencyUnit.pgk: return "Papua New Guinean Kina";
      case CurrencyUnit.php: return "Philippine Peso";
      case CurrencyUnit.pkr: return "Pakistani Rupee";
      case CurrencyUnit.pln: return "Polish Złoty";
      case CurrencyUnit.pyg: return "Paraguayan Guaraní";
      case CurrencyUnit.qar: return "Qatari Riyal";
      case CurrencyUnit.ron: return "Romanian Leu";
      case CurrencyUnit.rsd: return "Serbian Dinar";
      case CurrencyUnit.rub: return "Russian Ruble";
      case CurrencyUnit.rwf: return "Rwandan Franc";
      case CurrencyUnit.sar: return "Saudi Riyal";
      case CurrencyUnit.sbd: return "Solomon Islands Dollar";
      case CurrencyUnit.scr: return "Seychellois Rupee";
      case CurrencyUnit.sdg: return "Sudanese Pound";
      case CurrencyUnit.sek: return "Swedish Krona";
      case CurrencyUnit.sgd: return "Singapore Dollar";
      case CurrencyUnit.shp: return "Saint Helena Pound";
      case CurrencyUnit.sle: return "Sierra Leonean Leone";
      case CurrencyUnit.sll: return "Leone";
      case CurrencyUnit.sos: return "Somali Shilling";
      case CurrencyUnit.srd: return "Surinamese Dollar";
      case CurrencyUnit.ssp: return "South Sudanese Pound";
      case CurrencyUnit.stn: return "São Tomé and Príncipe Dobra";
      case CurrencyUnit.syp: return "Syrian Pound";
      case CurrencyUnit.szl: return "Eswatini Lilangeni";
      case CurrencyUnit.thb: return "Thai Baht";
      case CurrencyUnit.tjs: return "Tajikistani Somoni";
      case CurrencyUnit.tmt: return "Turkmenistani Manat";
      case CurrencyUnit.tnd: return "Tunisian Dinar";
      case CurrencyUnit.top: return "Tongan Paʻanga";
      case CurrencyUnit.try_: return "Turkish Lira";
      case CurrencyUnit.ttd: return "Trinidad and Tobago Dollar";
      case CurrencyUnit.tvd: return "Tuvaluan Dollar";
      case CurrencyUnit.twd: return "New Taiwan Dollar";
      case CurrencyUnit.tzs: return "Tanzanian Shilling";
      case CurrencyUnit.uah: return "Ukrainian Hryvnia";
      case CurrencyUnit.ugx: return "Ugandan Shilling";
      case CurrencyUnit.uyu: return "Uruguayan Peso";
      case CurrencyUnit.uzs: return "Uzbekistani Som";
      case CurrencyUnit.ves: return "Venezuelan Bolívar";
      case CurrencyUnit.vnd: return "Vietnamese Đồng";
      case CurrencyUnit.vuv: return "Vanuatu Vatu";
      case CurrencyUnit.wst: return "Samoan Tālā";
      case CurrencyUnit.xaf: return "Central African CFA Franc";
      case CurrencyUnit.xcd: return "East Caribbean Dollar";
      case CurrencyUnit.xcg: return "Caribbean Guilder";
      case CurrencyUnit.xdr: return "Special Drawing Rights";
      case CurrencyUnit.xof: return "West African CFA Franc";
      case CurrencyUnit.xpf: return "CFP Franc";
      case CurrencyUnit.yer: return "Yemeni Rial";
      case CurrencyUnit.zar: return "South African Rand";
      case CurrencyUnit.zmw: return "Zambian Kwacha";
      case CurrencyUnit.zwg: return "Zimbabwe Gold";
      case CurrencyUnit.zwl: return "Zimbabwean Dollar";
      }
  }
}